import { BreadcrumbSet } from '../../services/breadcrumb.service';

export const breadcrumbMap: Array<BreadcrumbSet> = [
  { path: 'pages', label: 'Pages' },
  { path: 'pages/ng', label: 'Angular' },
  { path: 'pages/ng/versions', label: 'Version' },
  { path: 'pages/ng/features', label: 'Features' },
  { path: 'api-media-aggregator', label: 'API & Media Aggregator' },
  { path: 'api-media-aggregator/list', label: 'List' },
  { path: 'api-media-aggregator/flickr', label: 'Flikr' },
  { path: 'api-media-aggregator/youtube', label: 'YouTube' },
  { path: 'news', label: 'News' },
  { path: 'angular', label: 'Angular' },
  { path: 'unique-id-modal', label: 'Unique IDs in a modal' },
  { path: 'component-interactions', label: 'Component Interactions' },
  { path: 'form-samples', label: 'Form Samples' },
  { path: 'form-samples/validation', label: 'Validation' },
  { path: 'coding-challenges', label: 'Coding Challenges' },
  { path: 'coding-challenges/two-sums', label: 'Two Sums' },
  { path: 'coding-challenges/department-team', label: 'Dpartment Teams' },
  { path: 'seo-tools', label: 'SEO Tools' },
  { path: 'seo-tools/keywords-extractor', label: 'Keywords Extractor' },
  { path: 'seo-tools/description-validator', label: 'Description Validator' },
  { path: 'rxjs-samples', label: 'RxJs Samples' },
  { path: 'rxjs-samples/students-one', label: 'Students Programs 1' },
  { path: 'rxjs-samples/students-two', label: 'Students Programs 2' },
  { path: 'rxjs-samples/todo-one', label: 'TODO app 1' },
];